name: build-document
on:
  push:
    paths:
      - "**.tex"
  workflow_dispatch:

jobs:
  build-document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/render-latex
        id: render-latex
        with:
          root-file: Methods-of-Mathematical-Methods-and-Equations
      - uses: actions/upload-artifact@v3
        with:
          name: final-document
          path: "${{ steps.render-latex.outputs.output-dir }}/*.pdf"
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == main
    permissions:
      contents: write
    needs:
      - build-document
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: final-document
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pdf"
          prerelease: true
          name: "${{ github.sha }}"
